apiVersion: apps/v1
kind: Deployment
metadata:
  name: database-deployment
spec:
  replicas: 1
  selector:
    matchLabels: 
      component: web-database
  template:
    metadata:
      labels:
        component: web-database
    spec:
      volumes:
        -name: server-database
        persistentVolumeClaim:
          claimName: database-persistent-vlome-claim
      containers:
        - name: myDatabase
          image: databasename
          ports:
            - containerPort: 9999
          volumeMounts:
            - name: server-database
              mountPath: /var/lib/myDatabase/data
              subPath: serverData