apiVersion: apps/v1
kind: Deployment
metadata:
  name: server-deployment
spec:
  replicas: 2
  selector:
    matchLabels: 
      component: web-server
  template:
    metadata:
      labels:
        component: web-server
    spec:
      containers:
        - name: server
          image: sravanreddyguduru7/node-server:v1
          ports:
            - containerPort: 3000